services:
  - type: web
    name: algodsa
    env: python
    region: singapore
    plan: starter
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py seed_full_dsa_pattern_curriculum && python manage.py seed_problems && gunicorn config.wsgi:application --log-file -"
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: algodsa-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://algodsa.onrender.com"

databases:
  - name: algodsa-db
    databaseName: algodsa
    user: algodsa_user
    plan: starter
