# Generated by Django 6.0.7 on 2026-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_leetcode_synced',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='leetcode_submission_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
