# Generated by Django 6.0.7 on 2026-07-30 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_pattern'),
        ('submissions', '0003_submission_is_leetcode_synced_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_category', models.CharField(choices=[('off_by_one', 'Off-by-One Error'), ('empty_input', 'Empty / Null Input Edge Case'), ('integer_overflow', 'Integer / Bound Overflow'), ('tle', 'Time Limit Exceeded (Efficiency)'), ('pointer_bounds', 'Pointer Out of Bounds'), ('hash_collision', 'Hash Map Key Collision'), ('general_logic', 'General Logic Bug')], default='general_logic', max_length=40)),
                ('ai_remediation', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='problems.problem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_records', to='submissions.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mistake_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
