# Generated by Django 6.0.7 on 2026-07-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_leetcode_sync_user_leetcode_total_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gfg_total_solved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gfg_username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='last_gfg_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_stats_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
