# Generated by Django 6.0.7 on 2026-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('cpp', 'C++'), ('java', 'Java'), ('python', 'Python'), ('javascript', 'JavaScript'), ('go', 'Go'), ('rust', 'Rust'), ('typescript', 'TypeScript'), ('csharp', 'C#')], default='python', max_length=20),
        ),
    ]
