# Generated by Django 6.0.7 on 2026-07-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('pattern', models.CharField(choices=[('two_pointers', 'Two Pointers'), ('sliding_window', 'Sliding Window'), ('binary_search', 'Binary Search'), ('bfs', 'BFS'), ('dfs', 'DFS'), ('dynamic_programming', 'Dynamic Programming'), ('greedy', 'Greedy'), ('backtracking', 'Backtracking'), ('hash_map', 'Hash Map'), ('stack', 'Stack'), ('queue', 'Queue'), ('linked_list', 'Linked List'), ('tree_traversal', 'Tree Traversal'), ('graph_traversal', 'Graph Traversal'), ('sorting', 'Sorting'), ('recursion', 'Recursion'), ('bit_manipulation', 'Bit Manipulation'), ('math', 'Math'), ('string_manipulation', 'String Manipulation'), ('heap', 'Heap')], max_length=30)),
                ('starter_code_python', models.TextField(blank=True, default='')),
                ('starter_code_javascript', models.TextField(blank=True, default='')),
                ('starter_code_cpp', models.TextField(blank=True, default='')),
                ('starter_code_java', models.TextField(blank=True, default='')),
                ('editorial', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('examples', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['order', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.topic'),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Direction'), (2, 'Level 2 - Pattern'), (3, 'Level 3 - Pseudocode')])),
                ('content', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='problems.problem')),
            ],
            options={
                'db_table': 'hints',
                'ordering': ['level'],
                'unique_together': {('problem', 'level')},
            },
        ),
    ]
