# Generated by Django 6.0.7 on 2026-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='real_world_analogy',
            field=models.TextField(blank=True, default=''),
        ),
    ]
