# Generated by Django 6.0.7 on 2026-07-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_topic_real_world_analogy'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='notes_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
