# Generated by Django 6.0.7 on 2026-07-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_topic_notes_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='⚡', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='problems.topic')),
            ],
            options={
                'db_table': 'patterns',
                'ordering': ['order', 'name'],
            },
        ),
    ]
