# Generated by Django 6.0.7 on 2026-08-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='visualization_type',
            field=models.CharField(blank=True, default='sliding_window', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='acceptance_rate',
            field=models.CharField(default='65%', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='company_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='est_time_mins',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='pattern_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.pattern'),
        ),
        migrations.AddField(
            model_name='problem',
            name='practice_tier',
            field=models.CharField(choices=[('concept_building', 'Concept Building (Easy)'), ('pattern_recognition', 'Pattern Recognition (Easy-Medium)'), ('pattern_mastery', 'Pattern Mastery (Medium)'), ('interview_ready', 'Interview Ready (Medium-Hard)'), ('expert', 'Expert (Hard)')], default='concept_building', max_length=30),
        ),
        migrations.AddField(
            model_name='problem',
            name='roadmap_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='starter_code_go',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='starter_code_rust',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('foundations', 'Foundations'), ('linear', 'Linear Data Structures'), ('non_linear', 'Non-Linear Data Structures'), ('algorithms', 'Algorithms & Techniques'), ('advanced', 'Advanced Data Structures'), ('math_bit', 'Math & Bit Manipulation')], default='linear', max_length=30),
        ),
        migrations.AddField(
            model_name='topic',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='topic',
            name='prerequisites',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('estimated_mins', models.PositiveIntegerField(default=20)),
                ('prerequisites', models.CharField(blank=True, default='', max_length=200)),
                ('overview', models.TextField(blank=True, default='')),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('real_world_analogy', models.TextField(blank=True, default='')),
                ('why_use', models.TextField(blank=True, default='')),
                ('when_use', models.TextField(blank=True, default='')),
                ('when_not_to_use', models.TextField(blank=True, default='')),
                ('math_intuition', models.TextField(blank=True, default='')),
                ('visualization_type', models.CharField(default='sliding_window', max_length=50)),
                ('code_python', models.TextField(blank=True, default='')),
                ('code_cpp', models.TextField(blank=True, default='')),
                ('code_java', models.TextField(blank=True, default='')),
                ('code_js', models.TextField(blank=True, default='')),
                ('code_go', models.TextField(blank=True, default='')),
                ('code_rust', models.TextField(blank=True, default='')),
                ('time_complexity_best', models.CharField(default='O(1)', max_length=50)),
                ('time_complexity_avg', models.CharField(default='O(N)', max_length=50)),
                ('time_complexity_worst', models.CharField(default='O(N)', max_length=50)),
                ('space_complexity', models.CharField(default='O(1)', max_length=50)),
                ('edge_cases', models.TextField(blank=True, default='')),
                ('common_mistakes', models.TextField(blank=True, default='')),
                ('interview_tips', models.TextField(blank=True, default='')),
                ('advanced_optimizations', models.TextField(blank=True, default='')),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='problems.pattern')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='problems.topic')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.lesson'),
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('love_babbar', 'Love Babbar'), ('striver_a2z', 'Striver A2Z'), ('neetcode', 'NeetCode Roadmap'), ('mit_stanford', 'MIT / Stanford OpenCourseWare')], default='striver_a2z', max_length=30)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=15)),
                ('youtube_url', models.URLField()),
                ('video_id', models.CharField(blank=True, default='', max_length=50)),
                ('duration', models.CharField(default='15m', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_resources', to='problems.lesson')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_resources', to='problems.pattern')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_resources', to='problems.topic')),
            ],
            options={
                'db_table': 'video_resources',
                'ordering': ['order', 'title'],
            },
        ),
    ]
